# Generated by Django 3.2.7 on 2021-09-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.CharField(max_length=9, verbose_name='Chat id')),
                ('firstName', models.CharField(max_length=64, verbose_name='First name')),
                ('lastName', models.CharField(max_length=64, verbose_name='Last name')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
            ],
        ),
    ]
